/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.keresman.editor.view.projects;

import com.keresman.editor.model.FileTreeModel;
import java.awt.Component;
import java.awt.EventQueue;
import java.io.File;
import java.io.IOException;
import java.nio.file.AccessDeniedException;
import java.nio.file.FileVisitResult;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.SimpleFileVisitor;
import java.nio.file.attribute.BasicFileAttributes;
import javax.swing.JTree;
import javax.swing.tree.DefaultTreeCellRenderer;

/**
 *
 * @author josip
 */
public class ProjectTreePanelDesigner extends javax.swing.JPanel {

    /**
     * Creates new form ProjectTreePanelDesigner
     */
    public ProjectTreePanelDesigner() {
        initComponents();
        initTree();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        trProjects = new javax.swing.JTree();

        setPreferredSize(new java.awt.Dimension(200, 800));
        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(240, 362));

        trProjects.setModel(null);
        trProjects.setName(""); // NOI18N
        trProjects.setPreferredSize(new java.awt.Dimension(200, 800));
        jScrollPane1.setViewportView(trProjects);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void initTree() {
        trProjects.setCellRenderer(new DefaultTreeCellRenderer() {
            @Override
            public Component getTreeCellRendererComponent(
                    JTree tree,
                    Object value,
                    boolean selected,
                    boolean expanded,
                    boolean leaf,
                    int row, boolean hasFocus
            ) {

                if (leaf) {
                    setIcon(leafIcon);
                } else {
                    setIcon(expanded ? openIcon : closedIcon);
                }

                File file = (File) value;

                setText(file.getName().isEmpty() ? file.getPath() : file.getName());

                return this;
            }
        });

        new Thread(() -> {
            try {
                findFile(System.getProperty("user.dir"), "EditorPanelDesigner.java");
            } catch (IOException e) {
                e.printStackTrace();
            }
        }).start();
    }

    private void findFile(String path, String filename) throws IOException {
        Path rootPath = Paths.get(path);
        Files.walkFileTree(rootPath, new SimpleFileVisitor<Path>() {
            @Override
            public FileVisitResult visitFile(Path file, BasicFileAttributes attrs) throws IOException {
                if (file.endsWith(filename)) {
                    setTreeModel(rootPath.toFile(), file.toFile());
                    return FileVisitResult.TERMINATE;
                }
                return FileVisitResult.CONTINUE;
            }

            @Override
            public FileVisitResult visitFileFailed(Path file, IOException exc) throws IOException {
                if (exc instanceof AccessDeniedException) {
                    return FileVisitResult.SKIP_SUBTREE;
                }
                return super.visitFileFailed(file, exc);
            }
        });
    }

    private void setTreeModel(File root, File targetFile) {
        EventQueue.invokeLater(
                () ->  trProjects.setModel(new FileTreeModel(root, targetFile)));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JTree trProjects;
    // End of variables declaration//GEN-END:variables
}
