/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.keresman.editor.view;

/**
 *
 * @author josip
 */
public class EditorPanelDesigner extends javax.swing.JPanel {

    /**
     * Creates new form EditorPanel
     */
    public EditorPanelDesigner() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tpContent = new javax.swing.JTextPane();

        setPreferredSize(new java.awt.Dimension(1080, 800));
        setLayout(new java.awt.BorderLayout());

        tpContent.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tpContentComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(tpContent);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tpContentComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tpContentComponentShown
        tpContent.setText("Milica je usla u sumu!!!");
    }//GEN-LAST:event_tpContentComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane tpContent;
    // End of variables declaration//GEN-END:variables
}
